name: Test default variables

on: 
  - push
  - workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest   
    steps:
      - name: check
        run: echo "GITHUB_Repository $GITHUB_REPOSITORY"
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: check2
        env:
          GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
          GITHUB_JOB: $GITHUB_JOB
          GITHUB_OUTPUT: $GITHUB_OUTPUT
          GITHUB_PATH: $GITHUB_PATH
        run: |
          echo "event_name: $GITHUB_EVENT_NAME"
          echo "job: $GITHUB_JOB"
          echo "output: $GITHUB_OUTPUT"
          echo "path: $GITHUB_PATH"
          echo "os: $RUNNER_OS"   