name: Test Output 
on: [push,workflow_dispatch,create  ]
jobs:
  Job-01:
    runs-on: ubuntu-latest
    steps:
        - name: Set the value
          id: step_one
          run: |
            echo "action_state=yellow" >> "$GITHUB_ENV"
        - name: Use the value
          id: step_two
          run: |
            printf '%s\n' "$action_state" # This will output 'yellow'
  Job-02:
    runs-on: ubuntu-latest
    if: ${{ github.event_name }} != 'push'
    steps:
        - name: Set the value
          id: step_one
          run: |
            echo "state=red" >> "$GITHUB_ENV"
        - name: Use the value
          id: step_two
          run: |
            printf '%s\n' "$state and $country"
          env:
            country: purple
  Job-03:
    runs-on: ubuntu-latest
    steps:
        - name: print-github-context
          run: echo ${{ github.event }}                