name: Test default variables

on: 
  - push
  - workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest   
    steps:
      - name: check
        run: echo "GITHUB_Repository $GITHUB_REPOSITORY"
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: check2
        env:
          GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
          GITHUB_JOB: $GITHUB_JOB
        run: |
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_JOB   